### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by hnbigfish** [chianjin/zhvt-classic#2]
怎么找不到jiazhu.sty呀。
谢谢
![Snipaste_2022-08-15_10-55-50](https://user-images.githubusercontent.com/72776767/184569667-b87fd767-536e-4825-aa2a-cea46197565c.jpg)

**Comment by chianjin** [comment]
夹注包见这里 https://github.com/CTeX-org/ctex-kit/tree/master/jiazhu
安装方法见这里 https://github.com/CTeX-org/ctex-kit/issues/630

**Comment by ctzhang2008** [comment]
执行tex jiazhu.dtx，出现以下问题，请教是什么原因。谢谢！
![Snipaste_2022-08-19_15-16-35](https://user-images.githubusercontent.com/3394174/185566491-2b725ad6-3218-4ae1-ab3e-6c5688e46ec0.png)

**Comment by MackenzieMen** [comment]
出现“？”输入“R”就可以解决了 @ctzhang2008
