### ISSUE TITLE
\mark_new_class:n功能报错

### ISSUE THREAD

**Issue by Wingong** [chianjin/zhvt-classic#3]
我试着编译了您的例程，但是程序报错Undefined control sequence. \mark_new_class:n，在知乎上也有人在您文章下提了相同的问题，查了半天发现可能是因为这个功能是今年6月的核心中提供的（ltmarks），我安装的是TeX Live 2022（用的XeLaTeX编译），里面没有相关文件。

我是纯TeX新手，只知道用发行版，想问一下您是怎么安装/编译的TeX环境呢？或者有没有能更新内核的方法？

期待您的解答

**Comment by chianjin** [comment]
有可能是你所说的问题。更新 texlive 试试看，`tlmgr update --all`。

**Comment by Wingong** [comment]
执行tlmgr update --self和tlmgr update --all后成功编译，感谢！
