### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Oliver-F1** [chianjin/zhvt-classic#5]
![图片](https://github.com/chianjin/zhvt-classic/assets/59132857/eaa72970-adaa-42ad-af24-72d7b24a5b92)
卡住了，网上也没找到解决办法，请问作者是否遇到此错误？

**Comment by chianjin** [comment]
更新到最新的 TeXLive 试试。另外，模板已经重新编写，使用方法请阅读 README 文件。
