### ISSUE TITLE
請教一下

### ISSUE THREAD

**Issue by M4STERCheng** [chianjin/zhvt-classic#7]
如果我想編排易經，怎麽輸出卦象符號呢

**Comment by chianjin** [comment]
两种解决方案

1、Unicode 已经收录八卦和六十四卦符号。前提是找到包含这些符号的字体。具体用法请见这里
[Displaying the 64 hexagrams of the Yi Jing (using Unicode range 4DC0 up 4DFF)](https://tex.stackexchange.com/questions/132437/displaying-the-64-hexagrams-of-the-yi-jing-using-unicode-range-4dc0-up-4dff)

2、制作八卦和六十卦符号的矢量图片转换为单个pdf，以图片方式插入正文。

**Comment by M4STERCheng** [comment]
十分感谢使用
```tex
%设置八卦字体
\newCJKfontfamily{\dejavusanszh}{DejaVu Sans}[RawFeature={vertical:+vert:+vhal}]
\newfontface{\dejavusans}{DejaVu Sans} % this font has the required glyphs

\newcommand{\iching}[1]{{\dejavusanszh\char\numexpr"4DC0+#1}}
\newcommand{\trigram}[1]{{\dejavusans\char\numexpr"2630+#1}}
```
已经实现
